### ISSUE TITLE
Getting started with this

### ISSUE THREAD

**Issue by samnazarko** [turtledesign/royalmail-php#7]
Hi

We're quite tired of DMO, so we've looked at using the Royal Mail shipping API to improve productivity. I was quite surprised to see this SDK available and went to give it a try. 

I'm trying to follow the example to create a shipment, as outlined in the Wiki, but I always get the following message when I print $response->getDebugInfo(). 

```
RoyalMail\Exception\ResponseException: Authorization Failure in /var/www/api-project/vendor/turtledesign/royalmail-php/src/RoyalMail.php:83
Stack trace:
#0 /var/www/api-project/vendor/turtledesign/royalmail-php/src/RoyalMail.php(67): RoyalMail\RoyalMail->send('createShipment', Array)
#1 [internal function]: RoyalMail\RoyalMail->processAction('createShipment', Array)
#2 /var/www/api-project/vendor/turtledesign/royalmail-php/src/RoyalMail.php(168): call_user_func_array(Array, Array)
#3 /var/www/api-project/test.php(45): RoyalMail\RoyalMail->__call('createShipment', Array)
```

I've put my client and secret in correctly for sure.

For Application ID, do you use RMG-API-G-01, or the application ID that you created via the Royal Mail Developer website that is meant to include your account number?

For username and password, do you use your developer login details or the credentials emailed? I tried using the credentials in the email but I'm still getting an authentication issue. I've contacted Royal Mail to clarify that my credentials are indeed valid, but wanted to check if I've missed anything obvious here as well.

Cheers

**Comment by samnazarko** [comment]
Got it working now: looks like I may have been sent the wrong credentials.
